window.NIU_CAPTIONS = {
  times: [
    [0, 16], [16, 48], [48, 92], [92, 140], [140, 188], [188, 240],
    [240, 300], [300, 360], [360, 430], [430, 500], [500, 580], [580, 660],
    [660, 740], [740, 820], [820, 900], [900, 980], [980, 1060], [1060, 1140],
    [1140, 1230], [1230, 1320], [1320, 1410], [1410, 1500], [1500, 1590], [1590, 1680],
    [1680, 1770], [1770, 1860], [1860, 1960], [1960, 2060], [2060, 2160], [2160, 2260],
    [2260, 2360], [2360, 2460], [2460, 2560], [2560, 2660], [2660, 2760], [2760, 2860],
    [2860, 2960], [2960, 3060], [3060, 3160], [3160, 3260], [3260, 3360], [3360, 3460],
    [3460, 3560], [3560, 3660], [3660, 3760], [3760, 3860], [3860, 3960], [3960, 4060],
    [4060, 4160], [4160, 4260], [4260, 4360], [4360, 4460], [4460, 4560], [4560, 4660],
    [4660, 4760], [4760, 4860], [4860, 4960], [4960, 5060], [5060, 5160],
  ],
  lines: {
    en: [
      "Niu Lai.",
      "A timid calf is born into the herd.",
      "His mother keeps him close. The world already feels too large.",
      "A skylark watches him grow.",
      "Fear is the first language he learns.",
      "He lives in the shelter of his mother and the herd.",
      "One day the skylark leads him away.",
      "He tumbles into a long, immersive dream.",
      "The grassland inside the dream has no edge.",
      "A spirit serpent finds him.",
      "This world offers no true safety.",
      "You must learn vigilance. You must stand on your own.",
      "Niu Lai does not yet understand. He keeps the words.",
      "He meets Bao La, a leopard who is brave and just.",
      "Bao La walks beside the lonely calf.",
      "The herd begins to move.",
      "The cattle do not trust the leopard.",
      "Wolves wait on the grass.",
      "Bao La draws the pack away.",
      "The herd is spared. They still turn from him.",
      "Peace does not last.",
      "The wolves return.",
      "They take members of the herd.",
      "Bao La leaps to defend them.",
      "Niu Lai’s mother puts herself between the danger and her son.",
      "She buys him a chance to run.",
      "She does not come back.",
      "The calf has to carry what she left.",
      "He learns the weight of a name.",
      "Humans cut into the forest with machines.",
      "Niu Lai stands in their way.",
      "He is no longer only afraid.",
      "The dream begins to thin.",
      "He wakes.",
      "The dream is over. The courage is not.",
      "Responsibility stays in his body.",
      "He understands what it is to protect.",
      "He faces danger head-on.",
      "The herd is ahead.",
      "His father leads them.",
      "The father speaks of the milk, of its flavor, of home.",
      "Niu Lai walks back to them.",
      "He is still a calf. He is not the same calf.",
      "The skylark is in the air again.",
      "The grassland holds.",
      "He takes his place in the line.",
      "The herd moves on.",
      "Niu Lai has learned how to arrive.",
      "The end.",
    ],
    es: [
      "Niu Lai.",
      "Un ternero tímido nace en la manada.",
      "Su madre lo mantiene cerca. El mundo ya se siente demasiado grande.",
      "Una alondra lo ve crecer.",
      "El miedo es el primer idioma que aprende.",
      "Vive al amparo de su madre y de la manada.",
      "Un día la alondra lo lleva lejos.",
      "Cae en un sueño largo e inmersivo.",
      "La pradera dentro del sueño no tiene borde.",
      "Una serpiente espíritu lo encuentra.",
      "Este mundo no ofrece una seguridad verdadera.",
      "Debes aprender vigilancia. Debes sostenerte solo.",
      "Niu Lai aún no entiende. Guarda las palabras.",
      "Conoce a Bao La, un leopardo valiente y justo.",
      "Bao La camina junto al ternero solitario.",
      "La manada empieza a moverse.",
      "El ganado no confía en el leopardo.",
      "Los lobos esperan en la hierba.",
      "Bao La aleja a la manada de lobos.",
      "La manada se salva. Aun así le dan la espalda.",
      "La paz no dura.",
      "Los lobos regresan.",
      "Se llevan a miembros de la manada.",
      "Bao La salta para defenderlos.",
      "La madre de Niu Lai se pone entre el peligro y su hijo.",
      "Le compra una oportunidad para correr.",
      "Ella no vuelve.",
      "El ternero debe cargar lo que ella dejó.",
      "Aprende el peso de un nombre.",
      "Los humanos cortan el bosque con máquinas.",
      "Niu Lai se cruza en su camino.",
      "Ya no es solo miedo.",
      "El sueño empieza a adelgazarse.",
      "Despierta.",
      "El sueño terminó. El valor no.",
      "La responsabilidad se queda en su cuerpo.",
      "Entiende lo que es proteger.",
      "Enfrenta el peligro de frente.",
      "La manada está adelante.",
      "Su padre los gía.",
      "El padre habla de la leche, de su sabor, del hogar.",
      "Niu Lai camina de regreso.",
      "Sigue siendo un ternero. No es el mismo ternero.",
      "La alondra vuelve al aire.",
      "La pradera se sostiene.",
      "Ocupa su lugar en la fila.",
      "La manada sigue.",
      "Niu Lai aprendió a llegar.",
      "Fin.",
    ],
    pt: [
      "Niu Lai.",
      "Um bezerro tímido nasce no rebanho.",
      "A mãe o mantém perto. O mundo já parece grande demais.",
      "Uma cotovia o vê crescer.",
      "O medo é a primeira língua que ele aprende.",
      "Ele vive ao abrigo da mãe e do rebanho.",
      "Um dia a cotovia o leva embora.",
      "Ele cai num sonho longo e imersivo.",
      "O campo dentro do sonho não tem borda.",
      "Uma serpente espírito o encontra.",
      "Este mundo não oferece segurança verdadeira.",
      "Você precisa aprender vigilância. Precisa se sustentar sozinho.",
      "Niu Lai ainda não entende. Ele guarda as palavras.",
      "Ele encontra Bao La, um leopardo corajoso e justo.",
      "Bao La caminha ao lado do bezerro solitário.",
      "O rebanho começa a se mover.",
      "O gado não confia no leopardo.",
      "Lobos esperam na grama.",
      "Bao La afasta a alcateia.",
      "O rebanho se salva. Ainda assim lhe viram as costas.",
      "A paz não dura.",
      "Os lobos voltam.",
      "Eles levam membros do rebanho.",
      "Bao La salta para defendê-los.",
      "A mãe de Niu Lai se põe entre o perigo e o filho.",
      "Ela compra para ele uma chance de correr.",
      "Ela não volta.",
      "O bezerro precisa carregar o que ela deixou.",
      "Ele aprende o peso de um nome.",
      "Humanos cortam a floresta com máquinas.",
      "Niu Lai se coloca no caminho deles.",
      "Ele já não é só medo.",
      "O sonho começa a rarear.",
      "Ele acorda.",
      "O sonho acabou. A coragem não.",
      "A responsabilidade fica no corpo dele.",
      "Ele entende o que é proteger.",
      "Ele enfrenta o perigo de frente.",
      "O rebanho está adiante.",
      "O pai os conduz.",
      "O pai fala do leite, do sabor, do lar.",
      "Niu Lai caminha de volta.",
      "Ainda é um bezerro. Não é o mesmo bezerro.",
      "A cotovia está no ar de novo.",
      "O campo se sustenta.",
      "Ele toma seu lugar na fila.",
      "O rebanho segue.",
      "Niu Lai aprendeu a chegar.",
      "Fim.",
    ],
    fr: [
      "Niu Lai.",
      "Un veau timide naît dans le troupeau.",
      "Sa mère le garde près d’elle. Le monde semble déjà trop vaste.",
      "Un alouette le voit grandir.",
      "La peur est la première langue qu’il apprend.",
      "Il vit à l’abri de sa mère et du troupeau.",
      "Un jour l’alouette l’entraîne au loin.",
      "Il bascule dans un long rêve immersif.",
      "La prairie du rêve n’a pas de bord.",
      "Un serpent-esprit le trouve.",
      "Ce monde n’offre aucune vraie sécurité.",
      "Tu dois apprendre la vigilance. Tu dois tenir seul.",
      "Niu Lai ne comprend pas encore. Il garde les mots.",
      "Il rencontre Bao La, un léopard brave et juste.",
      "Bao La marche auprès du veau solitaire.",
      "Le troupeau se met en marche.",
      "Les bêtes ne font pas confiance au léopard.",
      "Des loups attendent dans l’herbe.",
      "Bao La éloigne la meute.",
      "Le troupeau est sauvé. Ils lui tournent encore le dos.",
      "La paix ne dure pas.",
      "Les loups reviennent.",
      "Ils emportent des membres du troupeau.",
      "Bao La s’élance pour les défendre.",
      "La mère de Niu Lai se place entre le danger et son fils.",
      "Elle lui achète une chance de fuir.",
      "Elle ne revient pas.",
      "Le veau doit porter ce qu’elle a laissé.",
      "Il apprend le poids d’un nom.",
      "Des humains entament la forêt avec des machines.",
      "Niu Lai se dresse sur leur chemin.",
      "Il n’est plus seulement peur.",
      "Le rêve commence à s’amincir.",
      "Il s’éveille.",
      "Le rêve est fini. Le courage ne l’est pas.",
      "La responsabilité reste dans son corps.",
      "Il comprend ce que c’est que protéger.",
      "Il affronte le danger de face.",
      "Le troupeau est devant.",
      "Son père les guide.",
      "Le père parle du lait, de son goût, de la maison.",
      "Niu Lai revient vers eux.",
      "Il est encore un veau. Ce n’est plus le même veau.",
      "L’alouette est de nouveau dans l’air.",
      "La prairie tient.",
      "Il prend sa place dans la ligne.",
      "Le troupeau continue.",
      "Niu Lai a appris à arriver.",
      "Fin.",
    ],
    de: [
      "Niu Lai.",
      "Ein scheues Kalb wird in die Herde geboren.",
      "Die Mutter hält ihn nah. Die Welt wirkt schon zu groß.",
      "Eine Lerche sieht ihn wachsen.",
      "Furcht ist die erste Sprache, die er lernt.",
      "Er lebt im Schutz seiner Mutter und der Herde.",
      "Eines Tages führt die Lerche ihn fort.",
      "Er stürzt in einen langen, dichten Traum.",
      "Das Grasland im Traum hat keinen Rand.",
      "Eine Geisterschlange findet ihn.",
      "Diese Welt bietet keine echte Sicherheit.",
      "Du musst wachsam werden. Du musst allein stehen.",
      "Niu Lai versteht es noch nicht. Er behält die Worte.",
      "Er trifft Bao La, einen tapferen, gerechten Leoparden.",
      "Bao La geht neben dem einsamen Kalb.",
      "Die Herde setzt sich in Bewegung.",
      "Die Rinder trauen dem Leoparden nicht.",
      "Wölfe warten im Gras.",
      "Bao La lockt das Rudel fort.",
      "Die Herde bleibt verschont. Sie wenden sich trotzdem ab.",
      "Der Frieden hält nicht.",
      "Die Wölfe kehren zurück.",
      "Sie reißen Mitglieder der Herde.",
      "Bao La springt zu ihrer Verteidigung.",
      "Niu Lais Mutter stellt sich zwischen die Gefahr und ihren Sohn.",
      "Sie kauft ihm eine Chance zu laufen.",
      "Sie kommt nicht zurück.",
      "Das Kalb muss tragen, was sie hinterließ.",
      "Er lernt das Gewicht eines Namens.",
      "Menschen schneiden mit Maschinen in den Wald.",
      "Niu Lai stellt sich ihnen entgegen.",
      "Er ist nicht mehr nur Furcht.",
      "Der Traum wird dünn.",
      "Er erwacht.",
      "Der Traum ist vorbei. Der Mut nicht.",
      "Verantwortung bleibt in seinem Körper.",
      "Er begreift, was Schützen heißt.",
      "Er geht der Gefahr entgegen.",
      "Die Herde ist voraus.",
      "Sein Vater führt sie.",
      "Der Vater spricht von der Milch, von ihrem Geschmack, von zu Hause.",
      "Niu Lai geht zu ihnen zurück.",
      "Er ist noch ein Kalb. Es ist nicht dasselbe Kalb.",
      "Die Lerche ist wieder in der Luft.",
      "Das Grasland hält.",
      "Er nimmt seinen Platz in der Reihe.",
      "Die Herde zieht weiter.",
      "Niu Lai hat gelernt anzukommen.",
      "Ende.",
    ],
    it: [
      "Niu Lai.",
      "Un vitello timido nasce nel branco.",
      "La madre lo tiene vicino. Il mondo sembra già troppo grande.",
      "Un'allodola lo vede crescere.",
      "La paura è la prima lingua che impara.",
      "Vive al riparo della madre e del branco.",
      "Un giorno l'allodola lo porta via.",
      "Cade in un sogno lungo e immersivo.",
      "La prateria nel sogno non ha bordo.",
      "Un serpente spirito lo trova.",
      "Questo mondo non offre vera sicurezza.",
      "Devi imparare la vigilanza. Devi reggerti da solo.",
      "Niu Lai non capisce ancora. Tiene le parole.",
      "Incontra Bao La, un leopardo coraggioso e giusto.",
      "Bao La cammina accanto al vitello solo.",
      "Il branco inizia a muoversi.",
      "I bovini non si fidano del leopardo.",
      "I lupi aspettano nell'erba.",
      "Bao La allontana il branco di lupi.",
      "Il branco si salva. Gli voltano comunque le spalle.",
      "La pace non dura.",
      "I lupi tornano.",
      "Portano via membri del branco.",
      "Bao La salta per difenderli.",
      "La madre di Niu Lai si mette tra il pericolo e suo figlio.",
      "Gli compra una chance per correre.",
      "Lei non torna.",
      "Il vitello deve portare ciò che ha lasciato.",
      "Impara il peso di un nome.",
      "Gli umani tagliano la foresta con le macchine.",
      "Niu Lai si mette sulla loro strada.",
      "Non è più solo paura.",
      "Il sogno inizia a assottigliarsi.",
      "Si sveglia.",
      "Il sogno è finito. Il coraggio no.",
      "La responsabilità resta nel suo corpo.",
      "Capisce cosa significa proteggere.",
      "Affronta il pericolo di fronte.",
      "Il branco è davanti.",
      "Suo padre li guida.",
      "Il padre parla del latte, del sapore, di casa.",
      "Niu Lai torna da loro.",
      "È ancora un vitello. Non è lo stesso vitello.",
      "L'allodola è di nuovo in aria.",
      "La prateria tiene.",
      "Prende il suo posto in fila.",
      "Il branco va avanti.",
      "Niu Lai ha imparato ad arrivare.",
      "Fine.",
    ],
    id: [
      "Niu Lai.",
      "Seekor anak sapi pemalu lahir di kawanan.",
      "Ibunya menjaganya dekat. Dunia sudah terasa terlalu besar.",
      "Seekor burung skylark melihatnya tumbuh.",
      "Takut adalah bahasa pertama yang ia pelajari.",
      "Ia hidup dalam lindungan ibu dan kawanan.",
      "Suatu hari skylark membawanya pergi.",
      "Ia jatuh ke dalam mimpi yang panjang.",
      "Padang rumput di dalam mimpi tidak bertepi.",
      "Seekor ular roh menemukannya.",
      "Dunia ini tidak memberi keselamatan yang sungguh.",
      "Kau harus belajar waspada. Kau harus berdiri sendiri.",
      "Niu Lai belum mengerti. Ia menyimpan kata-kata itu.",
      "Ia bertemu Bao La, macan tutul yang berani dan adil.",
      "Bao La berjalan di samping anak sapi yang sunyi.",
      "Kawanan mulai bergerak.",
      "Sapi-sapi tidak percaya pada macan tutul.",
      "Serigala menunggu di rumput.",
      "Bao La menarik kawanan serigala menjauh.",
      "Kawanan terselamat. Mereka tetap memunggunginya.",
      "Damai tidak bertahan.",
      "Serigala kembali.",
      "Mereka membawa anggota kawanan.",
      "Bao La meloncat untuk melindungi mereka.",
      "Ibu Niu Lai berdiri antara bahaya dan anaknya.",
      "Ia membelikannya kesempatan untuk lari.",
      "Ia tidak kembali.",
      "Anak sapi harus menanggung apa yang ia tinggalkan.",
      "Ia belajar beratnya sebuah nama.",
      "Manusia memotong hutan dengan mesin.",
      "Niu Lai menghalangi jalan mereka.",
      "Ia bukan hanya takut lagi.",
      "Mimpi itu mulai menipis.",
      "Ia bangun.",
      "Mimpi selesai. Nyali tidak.",
      "Tanggung jawab tinggal di tubuhnya.",
      "Ia mengerti apa artinya melindungi.",
      "Ia menghadapi bahaya dari depan.",
      "Kawanan ada di depan.",
      "Ayahnya memimpin mereka.",
      "Ayah berbicara tentang susu, rasanya, tentang rumah.",
      "Niu Lai berjalan kembali.",
      "Ia masih anak sapi. Ia bukan anak sapi yang sama.",
      "Skylark ada di udara lagi.",
      "Padang rumput bertahan.",
      "Ia mengambil tempatnya dalam barisan.",
      "Kawanan terus berjalan.",
      "Niu Lai belajar bagaimana tiba.",
      "Tamat.",
    ]
  }
};
